import { raleway } from './fonts';

import Header from '@/components/Header';
import Footer from '@/components/Footer';

import '@/styles/main.scss';

export const metadata = {
	title: 'BELLIFY',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={raleway.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
